### ISSUE TITLE
I keep getting a CORS error

### ISSUE THREAD

**Issue by wanjohiryan** [LuanRT/google-this#13]
Access to XMLHttpRequest at 'https://google.com/search?q=twdg&aqs=chrome..69i57.1685j0j4&client=ms-android-motorola-rev2&sourceid=chrome-mobile&ie=UTF-8&aomd=1&start=0' from origin 'http://localhost:19006' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Do you have any way to bypass this?

**Comment by wanjohiryan** [comment]
I set up a custom proxy server. For those who might want to know.

**Comment by kyds3k** [comment]
@wanjohiryan can you give some more info on this? I'm getting the same error . . .

**Comment by Shankusu993** [comment]
Can you please elaborate on how did you do this?
