### ISSUE TITLE
Error: Could not search on Google: Request failed with status code 429

### ISSUE THREAD

**Issue by GeistFighter** [LuanRT/google-this#14]
Hey everyone,

Why i get "Error: Could not search on Google: Request failed with status code 429".

When i user the exemple code:

async function start() {
  const options = {
    page: 0, 
    safe: false, // hide explicit results?
    additional_params: { 
      // add additional parameters here, see https://moz.com/blog/the-ultimate-guide-to-the-google-search-parameters and https://www.seoquake.com/blog/google-search-param/
      hl: 'en' 
    }
  }
  
  const response = await google.search("TWDG", options);
  console.log(response); 
}

start();

**Comment by LuanRT** [comment]
Hello, status code 429 means you are being rate-limited by Google. If this is the first time you're using the library and got that right away then I assume Google might be blocking your IP address for some reason (Eg: maybe your IP is shared), in that case switching to a different IP will most likely fix the problem.

**Comment by GeistFighter** [comment]
Hello, it's really strange, indeed it's the first time I use your package, nevertheless my IP is dedicated, it doesn't seem to be banned from google I can reach my website from google for example.

**Comment by GeistFighter** [comment]
You will have a manipulation to make to deepen the research of the "why"?

**Comment by GeistFighter** [comment]
Now it works, I don't know why.

**Comment by LuanRT** [comment]
> Now it works, I don't know why.

Hello, so I've done a little testing on some remote servers and it seems to work fine even after spamming requests to the Google website. I feel like Google might have temporarily blocked incoming requests from your server's IP, if that happens again you can either wait or just change your server's IP address if possible.

**Comment by cdwmhcc** [comment]
It keeps prompting 429, and changing the IP cannot solve it. Testing with curl is not affected and works fine.

**Comment by cdwmhcc** [comment]
Testing with curl is not affected and works fine.
