### ISSUE TITLE
top_stories of the search, the 1st word was removed

### ISSUE THREAD

**Issue by GeistFighter** [LuanRT/google-this#15]
Hey,

When I use ".search" and find a top_stories, the first word was cut off.

Thanks to you !

Exemple:
![image](https://user-images.githubusercontent.com/42804270/151624718-47ec563a-76d2-4a89-9f0e-fab33d10c992.png)
Real link:
![image](https://user-images.githubusercontent.com/42804270/151624781-f965417c-72af-47d5-89f4-1667fab0a9c6.png)

**Comment by LuanRT** [comment]
Hello,
Thanks for reporting that! It must be a minor parsing problem, will fix it soon.

**Comment by GeistFighter** [comment]
Thanks you !
