### ISSUE TITLE
[1.2.9-d.3] SafeSearch still enabled regardless of option

### ISSUE THREAD

**Issue by xfrcc** [LuanRT/google-this#25]
## Expected Behavior
SafeSearch disabled when it should be
### Steps to Reproduce

`await google.image('something something nsfw', { safe: false });`
Request something NSFW in images, Throws error "Results for 'X' are hidden by SafeSearch"

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed
- [Yes] I have provided sufficient information

**Comment by LuanRT** [comment]
Are you sure? Just did some testing and it didn't block NSFW results. The library doesn't completely remove the `safe` parameter from the URL so that could be the problem, but it's hard to tell since I can't reproduce this.

**Comment by xfrcc** [comment]
I will test further soon
