### ISSUE TITLE
Does this only run on Nodejs

### ISSUE THREAD

**Issue by tbobker123** [LuanRT/google-this#30]
### Question

I am trying to import the library in a standard JS module but I get the error:

`Uncaught TypeError: Failed to resolve module specifier "googlethis". Relative references must start with either "/", "./", or "../".`

So I guess I need to run Node server for this to work? I'd like to include this as a pure front end library so I can integrate the functionality into a PHP Codeigniter project.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
I think a few packages googlethis depends on may be to blame for this. It'll probably work flawlessly in a browser after #26

**Comment by domaingenerator** [comment]
If you want any help rewriting this let me know, I would be happy to help you out.
