### ISSUE TITLE
The access rate limitation (ask)

### ISSUE THREAD

**Issue by akunerio** [LuanRT/google-this#32]
### Question

Did the google limit the access for this mechanism ? 

For example, I deploy this feature in server nodejs. Then there are 50-100 users simultaneously access this feature to get the search results. I worry google will block the access like a spam bot.

Thank you.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
I use this for a few projects and never faced a 429, but it might happen and honestly the only way to bypass it would be using proxies (ex: #29) or add some sort of delay between requests.

**Comment by akunerio** [comment]
I see. Thank you for your hard work. I will try to use that way.

**Comment by hugodlmm** [comment]
> I use this for a few projects and never faced a 429, but it might happen and honestly the only way to bypass it would be using proxies (ex: #29) or add some sort of delay between requests.

I'm getting error 429 after few search (without spamming) using boolean operators
