### ISSUE TITLE
v1.4.0 searching for images returns this error. it was working before

### ISSUE THREAD

**Issue by aymenitc** [LuanRT/google-this#35]
### Steps to reproduce

hello,
I just test this simple code and it returns error:
```
const images = await googlethis.image('The Wolf Among Us', { safe: false });
console.log(images); 
```

### Failure Logs

```shell
TypeError: Cannot read properties of null (reading '1')
at Object.image in googlethis/lib/core/main.js
```

### Expected behavior

it was working before as it return json results of search images

### Current behavior

it produces this error

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by danrfq** [comment]
Same issue here.

**Comment by LuanRT** [comment]
Hey everyone, sorry for the delay ~
Seems like the structure of the response changed, I'll try to reproduce & fix this later today.
Thanks!

**Comment by danrfq** [comment]
I got this error:
```bash
Uncaught SearchError: Unknown error
    at Object.image (\googlethis\lib\core\main.js:210:11)
```
The code is just `(async () => { await google.image("google") })()`.

**Comment by LuanRT** [comment]
> I got this error:
> 
> ```shell
> Uncaught SearchError: Unknown error
>     at Object.image (\googlethis\lib\core\main.js:210:11)
> ```
> 
> The code is just `(async () => { await google.image("google") })()`.

Update to v1.4.3 and let me know if it works, it should support Google's latest response structure.

**Comment by danrfq** [comment]
It's working now! Thank you so much.
