### ISSUE TITLE
Search Image doesn't work

### ISSUE THREAD

**Issue by bagusok** [LuanRT/google-this#42]
### Steps to reproduce

Search Images not work and returned []

<img width="670" alt="Screenshot 2023-01-07 203210" src="https://user-images.githubusercontent.com/52571584/211153487-1fd1931f-cb09-48e5-b0db-d20aea517374.png">
<img width="574" alt="Screenshot 2023-01-07 203150" src="https://user-images.githubusercontent.com/52571584/211153490-8565f2fe-a667-4061-9116-4b81b9c4b334.png">

### Failure Logs

```shell
[]
```

### Expected behavior

.

### Current behavior

.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Seems to be a similar problem to #41. Will look into it today.
Thanks for reporting!
