### ISSUE TITLE
image search doesn't have next page

### ISSUE THREAD

**Issue by whitestorm007** [LuanRT/google-this#47]
### Question

there is something  call nextPageToken or someting require to search more image 

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
This was possible before so it either broke due to recent changes made to the library or something changed in the API. I'll see if I can bring it back.
