### ISSUE TITLE
I am getting a CORS issue

### ISSUE THREAD

**Issue by SeniorEng** [LuanRT/google-this#48]
### Question

Access to XMLHttpRequest at 'https://google.com/search?q=ewwefwe&ie=UTF-8&aomd=1&start=0&hl=en' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am trying to use this GoogleThis API in React App.
Here is my codebase.

```
const options: object = {
    page: 0,
    safe: false,
    parse_ads: false,
    additional_params: {
      hl: "en",
    },
  };

const response = await google.search(searchString, options);
```

But currently I am getting a CORS issue, and I am not sure how to resolve this issue.

Could you please help me to solve this problem?

Thank you

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
You'll have to setup a cors proxy for that.

**Comment by hermesalvesbr** [comment]
Could you give detailed instructions on how to configure this proxy in your package?
