### ISSUE TITLE
Not getting any result on top stories

### ISSUE THREAD

**Issue by dtaubaso** [LuanRT/google-this#49]
### Question

I'm not getting any results on top stories with keywords that have top stories on serp. I even edited the code and saw that there are urls, but somehow got lost on the parsing process.

I was using as keywords "Lionel Messi" and "Joe Biden".

Thanks

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Haven't touched the stories parsing code in a long time, so there's probably something broken there. I'm guessing Google is using js to dynamically render these things but I could be wrong, maybe it's still possible to extract them.
