### ISSUE TITLE
Bad image results

### ISSUE THREAD

**Issue by Migushthe2nd** [LuanRT/google-this#51]
### Question

The image search feature returns many not very relevant or straight up bad images. And example of the module's results on the left
![image](https://user-images.githubusercontent.com/22274715/226911332-6173199d-a378-4ef5-8bb6-f86e45462399.png)
I'd like to use the module to search for product images. I have tried providing, `hl=nl`, `cr=countryNL` but this has not improved the results returned. I expect the module not to make requests with the same context as using google directly, but these current results are basically worthless.

Is it possible to improve these using some other query parameter?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Migushthe2nd** [comment]
Alright I switched to the Bing image search api. Managed to extract the API key WhatsApp uses to find suggested group icons.
Have fun `D41D8CD98F00B204E9800998ECF8427E4F4A7492`

**Comment by aehlke** [comment]
not stale
