### ISSUE TITLE
1.7.1 Search() function returning empty result list regardless of image passed

### ISSUE THREAD

**Issue by SOME-1HING** [LuanRT/google-this#52]
### Steps to reproduce

```
import fs from "fs/promises";
import google from "googlethis";

async function reverse(){
  const imageBuffer = await fs.readFile("./sample.jpg");
  const reverse = await google.search(imageBuffer, { ris: true });
  console.log(reverse);
};

reverse()
```

### Failure Logs

```shell
{
  results: [],
  videos: [],
  knowledge_panel: KnowledgeGraph {
    type: null,
    title: null,
    description: null,
    url: null,
    metadata: [],
    books: [],
    tv_shows_and_movies: [],
    ratings: [],
    available_on: [],
    images: [],
    songs: [],
    socials: [],
    demonstration: null,
    lyrics: null
  },
  featured_snippet: FeaturedSnippet { title: null, description: null, url: null },
  did_you_mean: null,
  weather: Weather {
    location: null,
    forecast: null,
    precipitation: null,
    humidity: null,
    temperature: null,
    wind: null,
    image: null
  },
  time: Time { hours: null, date: null },
  location: Location { title: null, distance: null, map: null },
  dictionary: Dictionary {
    word: null,
    phonetic: null,
    audio: null,
    definitions: [],
    examples: []
  },
  translation: Translation {
    source_language: null,
    target_language: null,
    source_text: null,
    target_text: null
  },
  top_stories: [],
  unit_converter: Converters {},
  people_also_ask: [],
  people_also_search: []
}
Error: TypeError: Cannot read properties of undefined (reading 'url')
    at Object.reverse (file:///C:/Users/***/Documents/GitHub/telegram-js-bot/src/GReverse.js:29:50)
    at async Object.callback (file:///C:/Users/***/Documents/GitHub/telegram-js-bot/index.js:57:20)
```

### Expected behavior

I was expecting the `search()` function to return a non-empty array with the search results, such as an array of image URLs or other relevant data. Specifically, I was not expecting the result to be an empty array like `{results: []}`.

### Current behavior

The current behavior is that the `search()` function is consistently returning an empty results list, represented as an empty array like `{results: []}`, regardless of the image that is passed as an argument. I have tested the function with multiple images, including those that were previously working before April, but it is still returning an empty results array.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by n-xsi** [comment]
Same issue over here

**Comment by n-xsi** [comment]
Same issue over here. Although, it seems they already know about it as there is already a closed issue on it

**Comment by Strooss** [comment]
same issue

**Comment by LuanRT** [comment]
For anyone reading this, sorry for the silence in this repo. I want to fix all the bugs and migrate it to TypeScript at some point but I always end up forgetting about it.

**Comment by Strooss** [comment]
Yes please changing to typescript will be heaven

**Comment by Johannes-Ptg** [comment]
has there been any update on this? i have the same issue right now, but would to make this work!

**Comment by ispyhumanfly** [comment]
I'm also experiencing the same issue.

**Comment by threeal** [comment]
It seems also happens on non image search. Any updates? @LuanRT

**Comment by kafkaesqu3** [comment]
I think they've changed the tag for the description: 
This returns no results: https://github.com/LuanRT/google-this/blob/5bca62f9f9ce7a0eb831f415781eea6055d250d2/lib/core/nodes/OrganicResults.js#L61

Resulting in statement this being false: https://github.com/LuanRT/google-this/blob/5bca62f9f9ce7a0eb831f415781eea6055d250d2/lib/core/nodes/OrganicResults.js#L128

Which means the results are never populated

**Comment by FraglyG** [comment]
this issue renders the entire package unusable, hoping a fix is applied soon

**Comment by christopher-inegbedion** [comment]
is the fix going to be merged any time soon?

**Comment by MonsterDKing** [comment]
2024 and dont work pls remove this package to npm ...

**Comment by respectabiggle** [comment]
bump
