### ISSUE TITLE
Is image search support text recognition?

### ISSUE THREAD

**Issue by kogakisaki** [LuanRT/google-this#64]
### Question

Is image search support text recognition?

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Nope. It's something I want to look into when rewriting this package though, I reckon it might not be possible as it's part of Google Lens.

**Comment by kogakisaki** [comment]
Good luck to you, I like your package. It's nice if you write a package that scrape Google Lens
