### ISSUE TITLE
Random error while calling in a loop

### ISSUE THREAD

**Issue by samuelbushi** [LuanRT/google-this#9]
**I'm searching images with a for loop, this happens randomly in one of the searches**

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

If I make 30 searches with a for loop, around 3 - 5 return this error. 

*This might be a mistake on my side, but after various attempts I'm clueless. 💀

**Comment by LuanRT** [comment]
I couldn't reproduce this. 
Does it only happen with specific queries?
If possible, provide more details such as code snippets so we can sort this out.

Also, make sure you have some delay between each search, Google might be rate limiting you.
